### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by LukeFlynn** [PantherKit/PantherKit-Core#1]
hi dere

wen i install the .git suppository into my mods folder, it does not load?

why do this happen?????

yurgent urgent

**Comment by Daniel12321** [comment]
Dickbutt

**Comment by LukeFlynn** [comment]
!!!!!! 

when I install dickbutt.git into mod folder it do no load....

spigotmc.org
spigotmc.org
spigotmc.org
spigotmc.org

**Comment by LukeFlynn** [comment]
@FerusGrim HELP!!!!!

**Comment by LukeFlynn** [comment]
@FerusGrim HELP!!!!!

**Comment by LukeFlynn** [comment]
@FerusGrim HELP!!!!!

**Comment by LukeFlynn** [comment]
@FerusGrim MAKE THIS PLUGIN WORK!

**Comment by LukeFlynn** [comment]
I SUBMIT A PULL REQUEST WITH DICK BUTT!

**Comment by LukeFlynn** [comment]
I WILL SUBMIT YOU TO A PULL REQUEST!

**Comment by LukeFlynn** [comment]
CAN I PLEASE BE PULLED INTO A REQUEST?

**Comment by LukeFlynn** [comment]
I REQUEST A PULL!

**Comment by LukeFlynn** [comment]
@Daniel12321 HALP!

**Comment by Daniel12321** [comment]
DICKBUTT SHALL RULE THIS PLUGIN

**Comment by LukeFlynn** [comment]
KINKY!!!!

**Comment by LukeFlynn** [comment]
@gravityfox!!

**Comment by FerusGrim** [comment]
Your concerns have been noted. Thank you for taking the time to help improve PantherKit-Core

Best Regards,
PantherKit Team

**Comment by LukeFlynn** [comment]
NO NO NO OPEN THIS! WE ARE NOT FINISHED HERE MISTER.

Best Regards,

Dickbutt Team and friends
